claim sessions and reconnect handlers done
amplement/janus-client pull request #1
Opened 2018-10-10 13:15 UTC by VivienAdnot

2018-10-10 13:16 UTC, VivienAdnot commented
![](https://github.trello.services/images/mini-trello-icon.png) [janus-client: claim session](https://trello.com/c/0UEiSGyo/723-janus-client-claim-session)

2018-10-10 14:35 UTC, cedbale requested changes

2018-10-10 14:35 UTC, cedbale commented on src/client/index.js
> +
remove line return

2018-10-10 14:35 UTC, cedbale approved these changes

2018-10-22 12:21 UTC, cedbale approved these changes

2018-10-22 12:22 UTC, merged